# Uncomment the block below and update the RPC URL to use the JSON-RPC fetcher.
# WIP, may not work with real data yet.

#[fetcher]
#type = "jsonrpc"
#rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
#chunk_size = 512

# Bootstrap mode... using a JSON file with all the events.
# The dojo-fixtures CLI tools can be used to generate this file.
# 
[fetcher]
type = "json"
file_path = "/tmp/pistols2.json"
chunk_size = 20000

[runtime]
process_events_batch_size = 2560
filter_concurrency = 1

[decoders.introspect]
store_path = "/tmp/pistols_json"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"

#[decoders.erc20]

#[decoders.erc721]

#[contracts.my_token]
#address = "0x42"
#decoders = ["erc20"]

[contracts.world]
address = "0x8b4838140a3cbd36ebe64d4b5aaf56a30cc3753c928a79338bf56c53f506c5"
decoders = ["introspect"]
deployed_at_block = 1376383

#[sinks.log]
#type = "log"
#label = "log-sink"

[sinks.sqlite]
type = "sqlite"
label = "sqlite"
database_url = "sqlite:///tmp/torii_core.sqlite"
clean_on_start = true
