# Uncomment the block below and update the RPC URL to use the JSON-RPC fetcher.
# WIP, may not work with real data yet.
[fetcher]
type = "jsonrpc"
rpc_url = "http://localhost:5050"
chunk_size = 512

[runtime]
process_events_batch_size = 2560
filter_concurrency = 1

[decoders.introspect]
store_path = "/tmp/local_json"
rpc_url = "http://localhost:5050"

#[decoders.erc20]

#[decoders.erc721]

#[contracts.my_token]
#address = "0x42"
#decoders = ["erc20"]

[contracts.world]
address = "0x079b90aa209a333d5c4b2621d121adeecdb7d705c81615a67944d4fb233c9666"
decoders = ["introspect"]

#[sinks.log]
#type = "log"
#label = "log-sink"

[sinks.sqlite]
type = "sqlite"
label = "sqlite"
database_url = "sqlite:///tmp/torii_core_local.sqlite"
clean_on_start = true
