[package]
name = "torii-introspect"
version = "0.1.0"
edition = "2021"
description = "Introspect indexer library for Torii"

[dependencies]


introspect-types = { path = "../../../introspect/crates/types" }


[build-dependencies]
tonic-build = "0.12"

[lints]
workspace = true
